### ISSUE TITLE
Final submission of Final Project - nkd2120

### ISSUE THREAD

**Issue by nicolaslonguetmarx** [QMSS-G5072-2020/final_project_nicolas_longuetmarx#1]
Hello, 

Here is my final project. There is also a document called **usage_legis_easy_download** that is the jupyter notebook example. 
Thank you!

0966eab

@tbrambor 
@SUN-Wenjun 
@lonadai0121

**Comment by lonadai0121** [comment]
3.5/5 Satisfactory Project: lack of complexity and breadth in skills; should not include your own API key in your package
1/3 Missing function documentation
3/3 The code is efficient, correct, and minimal
3/3 The package structure is clear, easy to follow, and closely matches the structure discussed in class.
2/3 There is some documentation for the package, data, and functions, but it is incomplete or difficult to follow.
3/3 The package installs without problems.
2.5/3 The package contains automated testing of at least some of the main functions but there're some small errors shown in the demo output.
